# Generated by Django 5.0.6 on 2024-07-01 11:46

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Department', models.CharField(choices=[('1', 'Sports Department'), ('2', 'Skill Department'), ('3', 'LSG Department'), ('4', 'Technical & Higher Education')], default='1', max_length=40)),
                ('Division', models.CharField(choices=[('1', 'Udaipur'), ('2', 'Jodhpur'), ('3', 'Kota'), ('4', 'Bikaner'), ('5', 'Jaipur'), ('6', 'Ajmer')], default='1', max_length=40)),
                ('Name_Of_Project', models.CharField(max_length=50)),
                ('Sanctioned_Amount', models.PositiveIntegerField(default=0)),
                ('Sanctioned_Amount_Date', models.DateField(default=datetime.date.today)),
                ('Technical_Sanctioned_Amount', models.PositiveIntegerField(default=0)),
                ('Technical_Sanctioned_Amount_Date', models.DateField(default=datetime.date.today)),
                ('Start_date', models.DateField(default=datetime.date.today)),
                ('Stipulated_Date_Of_Completion', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('leaves', models.IntegerField(default=1)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='PhysicalProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Of_Reporting', models.DateField()),
                ('Physical_Progress_Percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_progress_entries', to='employees.project')),
            ],
            options={
                'verbose_name': 'Physical Progress',
                'verbose_name_plural': 'Physical Progress',
            },
        ),
        migrations.CreateModel(
            name='AmountReleased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_Released_Date', models.DateField()),
                ('Amount_Released', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_released', to='employees.project')),
            ],
            options={
                'verbose_name': 'Amount Released',
                'verbose_name_plural': 'Amounts Released',
            },
        ),
        migrations.CreateModel(
            name='AmountReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_Received_Date', models.DateField()),
                ('Amount_Received', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_received', to='employees.project')),
            ],
            options={
                'verbose_name': 'Amount Received',
                'verbose_name_plural': 'Amounts Received',
            },
        ),
        migrations.CreateModel(
            name='TotalExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expenditure_Date', models.DateField(null=True)),
                ('Total_Expenditure', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_expenditures', to='employees.project')),
            ],
            options={
                'verbose_name': 'Total Expenditure',
                'verbose_name_plural': 'Total Expenditures',
            },
        ),
    ]
