# Generated by Django 5.0.6 on 2024-07-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
    ]
