# Generated by Django 5.0.6 on 2024-07-01 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20240701_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expenditure_date', models.DateField()),
                ('Expenditure_Value', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expenditure', to='employees.project')),
            ],
            options={
                'verbose_name': 'Physical Progress',
                'verbose_name_plural': 'Physical Progress',
            },
        ),
        migrations.DeleteModel(
            name='TotalExpenditure',
        ),
    ]
