# Generated by Django 5.0.6 on 2024-07-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_expenditure_delete_totalexpenditure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenditure',
            options={'verbose_name': 'Expenditure', 'verbose_name_plural': 'Expenditure'},
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='Expenditure_Value',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Project_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_handed_over', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='employees.project')),
            ],
            options={
                'verbose_name': 'Project Status',
                'verbose_name_plural': 'Project Status',
            },
        ),
    ]
