# Generated by Django 5.0.6 on 2024-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_expenditure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Division',
            field=models.CharField(choices=[('1', 'Udaipur'), ('2', 'Jodhpur'), ('3', 'Kota'), ('4', 'Bikaner'), ('5', 'Jaipur'), ('6', 'Ajmer'), ('7', 'Bharatpur')], default='1', max_length=40),
        ),
    ]
