# Generated by Django 5.0.6 on 2024-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_project_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Sanctioned_Amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='Technical_Sanctioned_Amount',
            field=models.FloatField(default=0),
        ),
    ]
