# Generated by Django 5.0.6 on 2024-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_project_sanctioned_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountreceived',
            name='Amount_Received',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='amountreleased',
            name='Amount_Released',
            field=models.FloatField(),
        ),
    ]
