# Generated by Django 5.0.6 on 2024-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_amountreceived_amount_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_handed_over',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Project_Status',
        ),
    ]
