# Generated by Django 5.0.6 on 2024-07-04 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_project_is_completed_project_is_handed_over_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Work_order_Amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='Work_order_Amount_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
