# Generated by Django 5.0.6 on 2024-07-08 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_project_work_order_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Client_Department',
            field=models.CharField(choices=[('Sports Department', 'Sports Department'), ('Skill Department', 'Skill Department'), ('LSG Department', 'LSG Department'), ('Technical & Higher Education', 'Technical & Higher Education')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='Division',
            field=models.CharField(choices=[('Udaipur', 'Udaipur'), ('Jodhpur', 'Jodhpur'), ('Kota', 'Kota'), ('Bikaner', 'Bikaner'), ('Jaipur', 'Jaipur'), ('Ajmer', 'Ajmer'), ('Bharatpur', 'Bharatpur')], default='1', max_length=40),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
