# Generated by Django 5.0.6 on 2024-07-10 19:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leaves',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='salary',
        ),
        migrations.AddField(
            model_name='project',
            name='Likely_Date_Of_Completion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='LikelyDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likely_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Likely_Date', to='employees.project')),
            ],
            options={
                'verbose_name': 'Likely_Date',
                'verbose_name_plural': 'Likely_Date',
            },
        ),
    ]
