# Generated by Django 5.0.6 on 2024-07-10 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Reporting_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
