# Generated by Django 5.0.6 on 2024-07-11 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_project_reporting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Reporting_Date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
