# Generated by Django 5.0.6 on 2024-07-11 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_project_reporting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='likelydate',
            name='Date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
