# Generated by Django 5.0.6 on 2024-07-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_likelydate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Budget_type',
            field=models.CharField(choices=[('Budget Ghoshna', 'Budget Ghoshna'), ('Non Budget Ghoshna', 'Non Budget Ghoshna')], default='1', max_length=40),
        ),
    ]
