# Generated by Django 5.0.6 on 2024-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_project_budget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Budget_type',
            field=models.CharField(choices=[('Budget Ghoshna', 'Budget Ghoshna'), ('Non Budget Ghoshna', 'Non Budget Ghoshna')], default='Budget Ghoshna', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='Client_Department',
            field=models.CharField(choices=[('Sports Department', 'Sports Department'), ('Skill Department', 'Skill Department'), ('LSG Department', 'LSG Department'), ('Technical & Higher Education', 'Technical & Higher Education')], default='Sports Department', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='Division',
            field=models.CharField(choices=[('Udaipur', 'Udaipur'), ('Jodhpur', 'Jodhpur'), ('Kota', 'Kota'), ('Bikaner', 'Bikaner'), ('Jaipur', 'Jaipur'), ('Ajmer', 'Ajmer'), ('Bharatpur', 'Bharatpur')], default='Udaipur', max_length=40),
        ),
    ]
