# Generated by Django 5.0.6 on 2024-07-12 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_project_budget_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='physical_progress',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='Division',
            field=models.CharField(choices=[('Udaipur', 'Udaipur'), ('Jodhpur', 'Jodhpur'), ('Kota', 'Kota'), ('Unit II', 'Unit II'), ('Unit III', 'Unit III'), ('Unit IV', 'Unit IV')], default='Udaipur', max_length=40),
        ),
    ]
