# Generated by Django 5.0.6 on 2024-07-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_expenditure_photo_expenditure_physical_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Expenditure/f"{self.project.Name_Of_Project}/%Y/%m/%d/'),
        ),
    ]
