# Generated by Django 5.0.6 on 2024-07-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_alter_expenditure_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Expenditure/'),
        ),
    ]
