# Generated by Django 5.0.6 on 2024-07-13 07:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_alter_expenditure_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completion_date', models.DateField()),
                ('Date', models.DateField(default=datetime.date.today, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Completion_date', to='employees.project')),
            ],
            options={
                'verbose_name': 'Completion_date',
                'verbose_name_plural': 'Completion_date',
            },
        ),
        migrations.CreateModel(
            name='HandoverDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Handover_date', models.DateField()),
                ('Date', models.DateField(default=datetime.date.today, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Handover_date', to='employees.project')),
            ],
            options={
                'verbose_name': 'Handover_date',
                'verbose_name_plural': 'Handover_date',
            },
        ),
    ]
