# Generated by Django 5.0.6 on 2024-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_completiondate_handoverdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='A_and_F_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='Technical_Sanctioned_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='Work_order_Number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
