# Generated by Django 5.0.6 on 2024-07-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_project_a_and_f_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Sanctioned_Amount',
            new_name='A_and_F_Amount',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Sanctioned_Amount_Date',
            new_name='A_and_F_Date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Technical_Sanctioned_Amount_Date',
            new_name='Technical_Sanctioned_Date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Work_order_Amount_Date',
            new_name='Work_order_Date',
        ),
    ]
