# Generated by Django 5.0.6 on 2024-07-13 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_rename_sanctioned_amount_project_a_and_f_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='A_and_F_Amount',
            field=models.FloatField(db_column='A&F_Amount', default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='A_and_F_Date',
            field=models.DateField(db_column='A&F_Date', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='A_and_F_Number',
            field=models.CharField(db_column='A&F_Number', max_length=50),
        ),
    ]
