# Generated by Django 5.0.6 on 2024-07-13 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_alter_project_a_and_f_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Financial_year',
            field=models.CharField(choices=[('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031')], default='2016-2017', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='A_and_F_Amount',
            field=models.FloatField(db_column='A&F_Amount', default=0, verbose_name='A&F Amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='A_and_F_Date',
            field=models.DateField(db_column='A&F_Date', default=datetime.date.today, verbose_name='A&F Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='A_and_F_Number',
            field=models.CharField(db_column='A&F_Number', max_length=50, verbose_name='A&F Number'),
        ),
    ]
