# Generated by Django 5.0.6 on 2024-07-13 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.TimeField(default=datetime.time(1, 1, 26, 952169), editable=False),
        ),
    ]
