# Generated by Django 5.0.6 on 2024-07-14 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_alter_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.TimeField(default=django.utils.timezone.localtime, editable=False),
        ),
    ]
