# Generated by Django 5.0.6 on 2024-07-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_alter_amountreceived_id_alter_amountreleased_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
