# Generated by Django 5.0.6 on 2024-07-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_project_parent_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Is_Splited',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40),
        ),
    ]
