# Generated by Django 5.0.6 on 2024-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_project_is_splited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='A_and_F_Amount',
            field=models.FloatField(blank=True, db_column='A&F_Amount', null=True, verbose_name='A&F Amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='A_and_F_Date',
            field=models.DateField(blank=True, db_column='A&F_Date', null=True, verbose_name='A&F Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='A_and_F_Number',
            field=models.CharField(blank=True, db_column='A&F_Number', max_length=50, null=True, verbose_name='A&F Number'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Budget_type',
            field=models.CharField(blank=True, choices=[('Budget Ghoshna', 'Budget Ghoshna'), ('Non Budget Ghoshna', 'Non Budget Ghoshna')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Client_Department',
            field=models.CharField(blank=True, choices=[('Sports Department', 'Sports Department'), ('Skill Department', 'Skill Department'), ('LSG Department', 'LSG Department'), ('Technical & Higher Education', 'Technical & Higher Education')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Division',
            field=models.CharField(blank=True, choices=[('Udaipur', 'Udaipur'), ('Jodhpur', 'Jodhpur'), ('Kota', 'Kota'), ('Unit II', 'Unit II'), ('Unit III', 'Unit III'), ('Unit IV', 'Unit IV')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Financial_year',
            field=models.CharField(blank=True, choices=[('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Is_Splited',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Name_Of_Project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
