# Generated by Django 5.0.7 on 2024-07-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0038_alter_project_client_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Division',
            field=models.CharField(blank=True, choices=[('Udaipur', 'Udaipur'), ('Jodhpur', 'Jodhpur'), ('Kota', 'Kota'), ('Unit II', 'Unit II'), ('Unit III', 'Unit III'), ('Unit IV', 'Unit IV')], max_length=40, null=True, verbose_name='Unit'),
        ),
    ]
