# Generated by Django 5.0.7 on 2024-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0039_alter_project_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Client_Department',
            field=models.CharField(blank=True, choices=[('Higher Education Department', 'Higher Education Department'), ('Department of Skill, Employment & Enterpreneurship', 'Department of Skill, Employment & Enterpreneurship'), ('Rajasthan State Sports Council', 'Rajasthan State Sports Council'), ('Youth Affairs & Sports( Khelo India)', 'Youth Affairs & Sports( Khelo India)'), ('Rajasthan State Pollution Control Board, Bhilwara', 'Rajasthan State Pollution Control Board, Bhilwara'), ('Government Engineering College, Ajmer', 'Government Engineering College, Ajmer'), ('Government Engineering College, Jhalawar', 'Government Engineering College, Jhalawar'), ('Shiksha Sankul Jaipur', 'Shiksha Sankul Jaipur'), ('DMFT-GovernmentPG College, Nathdwara', 'DMFT-GovernmentPG College, Nathdwara'), ('Rajasthan High Court Jodhpur', 'Rajasthan High Court Jodhpur'), ('Science & Technology Department', 'Science & Technology Department'), ('ITI Ajmer', 'ITI Ajmer'), ('ITI Sikar', 'ITI Sikar'), ('ITI Sikar', 'ITI Sikar'), ('ITI Kishangarh', 'ITI Kishangarh'), ('LSG Department', 'LSG Department'), ('Industries Department', 'Industries Department')], max_length=100, null=True),
        ),
    ]
