"""
Django settings for pms project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import os
from .info import *
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = DIR
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRETKEY
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []
# Application definition
INSTALLED_APPS = APPS
CRISPY_TEMPLATE_PACK = PACK
MIDDLEWARE = MIDDLEWARE 
ROOT_URLCONF = ROOT
TEMPLATES = TEMPLATES
WSGI_APPLICATION = WSGI
EMAIL_BACKEND =  EMAIL_BACKEND # During development only
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = PASSWORD_VAL
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = LANG
TIME_ZONE = TZ
USE_I18N = True
USE_L10N = True
USE_TZ = True
DATABASES =  DATABASE_INFO
DEFAULT_AUTO_FIELD = EMAIL
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
MEDIA_URL = MEDIA
STATIC_URL = STATIC
STATIC_ROOT = STATIC_R
STATICFILES_DIRS = STATIC_DIRS

